### ISSUE TITLE
Race Condition: Buy Order Not Complete Before Sell Order

### ISSUE THREAD

**Issue by rybolov** [gcarq/freqtrade#112]
If you make a buy and the order is not complete before you have a race condition and the bot stops.

2 options to resolve:
1 Check the wallet to make sure that sufficient coins are available.  This makes other problem scenarios: buy never completes, price changes drastically before the buy is complete, etc.  Maybe can do something like cancel the pending order, and sell what coins are available.
2 check order status and cancel a buy after a certain time if it's not fulfilled.  If the order is partial, then update the order table with the appropriate quantity.  This can also be used with a wallet check to make sure there is sufficient coins available.

Traceback (most recent call last):
  File "/home/rybolov/freqtrade/freqtrade/main.py", line 91, in _process
    state_changed = handle_trade(trade) or state_changed
  File "/home/rybolov/freqtrade/freqtrade/main.py", line 183, in handle_trade
    execute_sell(trade, current_rate)
  File "/home/rybolov/freqtrade/freqtrade/main.py", line 137, in execute_sell
    order_id = exchange.sell(str(trade.pair), limit, trade.amount)
  File "/home/rybolov/freqtrade/freqtrade/exchange/__init__.py", line 110, in sell
    return _API.sell(pair, rate, amount)
  File "/home/rybolov/freqtrade/freqtrade/exchange/bittrex.py", line 62, in sell
    amount=amount))
RuntimeError: INSUFFICIENT_FUNDS params=(BTC_EMC2, 1.508e-05, 1345.4275694631779)

**Comment by gcarq** [comment]
Right now option 2 is implemented, but it doesn't cancel the order, instead it waits until the whole order is marked as `closed` and updates the amount and rate accordingly. Maybe it doesn't handle partial orders correctly.
This logic should be handled in [Trade.update(...)](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/persistence.py#L79), which gets called in [main.py#L89](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/main.py#L89) with the attached `open_order_id`, and only `if open_order_id is None` the bot should try to sell.

Did any exceptions occur before that error, because it could be possible that some exception got raised and therefore the database update got lost.

Could you take a look at bittrex how the order `LIMIT_BUY` order for this trade looks like?
