### ISSUE TITLE
Sell due to loss, bot buys the same currency

### ISSUE THREAD

**Issue by cih997** [gcarq/freqtrade#118]
I set up loss limit to 5%, bot bought NEO, after a little while loss was 5.24% so bot sold NEO and right after that (few seconds later) bot bought NEO again. Does that make sense? If so - can we block that somehow? If not - can we block that somehow?

**Comment by hftcrypto** [comment]
Had that same issue as well on DODGE with the develop branch


BITTREX: Buying BTC/DOGE with limit 0.00000018

BITTREX: Selling BTC/DOGE with limit 0.00000016 (profit: ~-11.61%)

BITTREX: Buying BTC/DOGE with limit 0.00000018

BITTREX: Selling BTC/DOGE with limit 0.00000016 (profit: ~-11.61%)

BITTREX: Buying BTC/DOGE with limit 0.00000018

BITTREX: Selling BTC/DOGE with limit 0.00000016 (profit: ~-11.61%)

BITTREX: Buying BTC/DOGE with limit 0.00000017

**Comment by gcarq** [comment]
Thanks for reporting this, the fix should be fairly easy, we are already removing the currently opened trades as potential pair for the next trade here [main.py#L193](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/main.py#L193).

We have multiple options here:
1. also ignore *n* last recently used pairs
2. also ignore all pairs which are used within the last *m* minutes.
3. also ignore all pairs which hit stop limit with the last *m* minutes.

@hftcrypto What is the rough timeframe in your case?
@vertti What do you think about this?

**Comment by hftcrypto** [comment]
@gcarq Not sure which timeframe you are referring. But this happened Nov 19th. Note that before these subsequent trades it sold DODGE with +5.75% profit
![screen shot 2017-11-20 at 10 48 39 am](https://user-images.githubusercontent.com/7797999/33000023-7b25c944-cde0-11e7-8951-0585aef578ed.png)

Then it bought DODGE and sold it immediately.

![screen shot 2017-11-20 at 10 49 54 am](https://user-images.githubusercontent.com/7797999/33000057-b3740f7c-cde0-11e7-8705-b4c300ba0cf4.png)

The it continued with subsequent buying and selling..

![screen shot 2017-11-20 at 10 47 03 am](https://user-images.githubusercontent.com/7797999/32999966-31d2742c-cde0-11e7-9f7b-7b0c0a65fd0f.png)

**Comment by hftcrypto** [comment]
@gcarq maybe add to your fix to ignore pair closed with a profit in a day?

**Comment by gcarq** [comment]
@hftcrypto With timeframe I meant how many time has passed during these sells.
Yes I guess that makes sense

**Comment by andremog** [comment]
@hftcrypto @gcarq I believe this would be the best option:
3. also ignore all pairs which hit stop limit with the last m minutes.

In my experience there are pairs with subsequent profitable trades reasonably often (e.g. two or three trades in the same day). On the other hand, a pair which hit stop limit is more likely to reach it again in the short term. I suggest the parameter 'm' to be from 360 to 720 minutes.

**Comment by hftcrypto** [comment]
@gcarq seconds I guess you can see from the screenshot I had attached it was buying and selling fast like it was looping.

**Comment by jblestang** [comment]
If it is buying again then it means that the buy_signal is still ‘on’ ?

**Comment by hftcrypto** [comment]
@gcarq Based from my analysis on the issue I think it is best ignore all pairs used within a day. Either we are in profit or loss for a pair we will just look for other pairs for next opportunity.

**Comment by rybolov** [comment]
This is an algorithm tuning problem, not a timing problem.  Your tuning is making bad buys.  If you lost money on a trade through a limit and the bot immediately buys again and sells at a second loss, it's because you tuned the bot to buy at the bottom of the RSI/FASTD/OtherOscillator (ie, the range) not paying attention to if it was going up or down (plus/minus DI) and how fast it was moving (ADX).  And you bought going down.  But the version in master right now works this way.  I've had a huge conversation in Slack and offered up some different buy and sell signals that should fix the problem.

Each trade should be independent of each other.  There is no such thing as a "hot streak" or "losing streak".  You flip a penny 5 times and because the penny landed on heads 5 times in a row doesn't mean that it will land on tails next time.  Each coin toss is independent.  Back to the bot, if the buy signal is still there after a trade (good or bad), then make a purchase.

> 1. also ignore n last recently used pairs
> 2. also ignore all pairs which are used within the last m minutes.
> 3. also ignore all pairs which hit stop limit with the last m minutes.
#1 and #2 do not do this.  It doesn't allow me to re-buy a stock that is going up even though I just bought and sold it at a profit.  I want to buy again.  Especially in the way I do tuning, where I have multiple "OR" conditions for making a buy/sell.  Maybe I bought at the bottom of the range and sold after my upper limit switch was hit, but the price is still going up fast.  I should be able to buy based on that criteria.

#3 is "just OK", although I don't like it.  IE, if my bot is tuned it still might take a loss on a trade via stoploss but then what happens if it stops going down and starts to climb?  I should be able to by again and regain my loss.

>If it is buying again then it means that the buy_signal is still ‘on’ ?
Yes, and don't stop this behavior.  With the wild price swings in crypto, you have to get as much use out of the huge upswings as you can.

>I think it is best to ignore all pairs used within the day.
That's insane. =) =) =)  This is high-frequency trading in an extremely volatile market, not buy-hold-sell with stable stocks.

**Comment by rybolov** [comment]
Me: submitted a pull request for this.  Fixes the buy and sell strategy so that it doesn't buy when the price is below FASTD/RSI/ETC and still dropping.  Instead, it only buys when the price is rising.
https://github.com/gcarq/freqtrade/pull/135

**Comment by jblestang** [comment]
Getting weird results with the new strategy ! ![608c14ba-2cdd-4f8c-b1e6-155b3a0a86e0](https://user-images.githubusercontent.com/6736541/33186429-de5a8a12-d089-11e7-9421-46ccc3e6e79f.png)

**Comment by jblestang** [comment]
![33eef421-7822-461c-b57d-3c149398ee17](https://user-images.githubusercontent.com/6736541/33186697-dd47bc2e-d08b-11e7-829a-39d363a2c2a2.png)

**Comment by rybolov** [comment]
Can you post your config.json?  Sounds like a weird issue there.  I'm running this patch in production with my "real" money and it works great.

**Comment by hftcrypto** [comment]
@rybolov is the fix available on develop?

**Comment by jblestang** [comment]
And i’m Using —dynamic-whitelist

**Comment by hftcrypto** [comment]
@rybolov can you post your config.json? I too am getting losses maybe it's in my config. Thanks

**Comment by jblestang** [comment]
From the description of PR #135

Added Plus and Minus Directional Indicator and Directional Movement into dataframe.
Buy if at the low end of normal range and the price is increasing.
Buy into extreme gains regardless of if it's on the low part of the range.
Avoid buying when the price is on a long decrease even if it's low.
Sell anytime the price is above the top end of normal range and the momentum slows.
Sell on an extreme drop.

**Comment by jblestang** [comment]
Could it be a rounding a error? 

![68ffee85-432e-452b-9d56-090fa021b419](https://user-images.githubusercontent.com/6736541/33221419-a9acd7d6-d14f-11e7-979a-48420d8dbaf1.png)

**Comment by gcarq** [comment]
I've created a experimental feature flag called `use_sell_signal` which is set to false per default. Covered in PR #143 This is not a fix but a quick workaround.

@jblestang I also think this could related to rounding errors because it happens primarily with coins only worth some satoshis.

**Comment by jblestang** [comment]
I’ll have a linked @ issue #139 to implement a black lost of pairs not to be traded, not a fix either for this issue bit a way to avoid it.

**Comment by jblestang** [comment]
I was referring to issue #129 not #139

**Comment by devalias** [comment]
still getting:
echo, [16.12.17 12:43]
BITTREX: Buying BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000032

echo, [16.12.17 12:44]
BITTREX: Selling BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000031 (profit: ~-3.62%)

echo, [16.12.17 12:45]
BITTREX: Buying BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000031

echo, [16.12.17 12:48]
BITTREX: Selling BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000029 (profit: ~-3.83%)

echo, [16.12.17 12:49]
BITTREX: Buying BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000030

echo, [16.12.17 12:50]
BITTREX: Selling BTC/DOGE (https://www.bittrex.com/Market/Index?MarketName=BTC-DOGE) with limit 0.00000028 (profit: ~-7.17%)

**Comment by seansan** [comment]
We see this also sometimes - could send same pictures. I think we can solve this partially thru implementing 

https://github.com/gcarq/freqtrade/issues/316
https://github.com/gcarq/freqtrade/issues/320
https://github.com/gcarq/freqtrade/issues/325

**Comment by jblestang** [comment]
Can we consider that PR #395 is covering this and close this bug?

**Comment by glonlas** [comment]
I will close this bug this #395 is merged. 
Please feel free to reopen it if you still see this issue.
