### ISSUE TITLE
MIN_TRADE_REQUIREMENT_NOT_MET

### ISSUE THREAD

**Issue by alxnegrila** [gcarq/freqtrade#132]
"stake_amount": 0.0005

Traceback (most recent call last):
  File "./freqtrade/main.py", line 70, in _process
    trade = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 213, in create_trade
    order_id = exchange.buy(pair, buy_limit, amount)
  File "/vagrant/freqtrade/freqtrade/exchange/__init__.py", line 100, in buy
    return _API.buy(pair, rate, amount)
  File "/vagrant/freqtrade/freqtrade/exchange/bittrex.py", line 53, in buy
    amount=amount))
RuntimeError: MIN_TRADE_REQUIREMENT_NOT_MET params=(BTC_CLUB, 0.00067, 0.7444029850746269)

**Comment by gcarq** [comment]
Bittrex requires a minimum amount of 50k satoshi

**Comment by alxnegrila** [comment]
0.00067 is more than 50k satoshi, the stake_amount was set to 0.0005

**Comment by hftcrypto** [comment]
When this is encountered. The program crashes and bot stops. Is there anyway to handle this properly rather than just stopping the bot?

**Comment by alxnegrila** [comment]
I think this may happen in the following scenario:
1. Price drops to a certain point
2. Bot wants to buy X coins for price Y, that is 0.0005 BTC
3. Price drops even lower
4. The buy order is set but price is less than Y, that being less than 0.0005 BTC

**Comment by gcarq** [comment]
@alxnegrila 0.00067 is the rate at which it tried to buy CLUB it's not the amount.

Indeed, 0.0005 BTC should actually be fine.
The scenario was
Place LIMIT_BUY order to get 0.74440298 CLUB's for 0.0005 BTC at a rate of  0.00067 BTC/CLUB.

@hftcrypto Did you encounter the exact same traceback? As far as I can see the bot didn't crash at this point (the RuntimeError got catched in _process). It should stop, give you a telegram message about what failed and then you can /start it again.

Errors reported from bittrex are already catched, but they require human intervention.
Right now there is no reliable way to handle that because of several reasons:
* There is no public documentation which contains a complete list of all error codes
* You cannot just ignore these errors because it could mask a configuration problem and could lead to a banned account.

@alxnegrila it would be possible to require a minimum `stake_amount` but that would be very specific to BTC on bittrex.

I think I spotted the place where it misbehaves, it is somewhere within the fee calculation:
```
>>> 0.00067 * 0.7444029850746269
0.0004987500000000001
```
It acutally tried to create LIMIT_BUY order for 0.00049875 BTC

**Comment by gcarq** [comment]
Thanks for reporting this, the attached PR should fix it.
