### ISSUE TITLE
Send Message to Groups and Channels on Telegram 

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#163]
Enhancement: 
An Option to make the bot send status updates (trades) to telegram groups and channels!

**Comment by timhilliard** [comment]
This is already possible. I am sending my status updates to a group. The trick is that you need to get the group id and put it into the chat_id parameter of the config instead of your own user id.

The easiest way I found to get this was by using Telegram Web and then going to the group you want to add the status updates to. The group id will be in the url. More instructions for this can be found at https://github.com/GabrielRF/telegram-id/blob/master/README.md

**Comment by amaanr** [comment]
Curious @timhilliard, did you do anything extra to make sure the `/stop` and `/forcesell` commands are not executable by anyone in the group?

**Comment by timhilliard** [comment]
No, it was a private group and i trusted the other participant (my wife) so didn't have to worry about that. But I could definitely see that being a problem.

**Comment by xmatthias** [comment]
I think i've said it before - but the telegram bot we use in freqtrade is not intended to be used by a group chat, but by the owner himself to control things.

I assume it's more about the notification part (posting profits / losses) - in which case you should be able to use the webhooks in combination with IFTTT - and use a telegram bot from there.

That'll mean no command can be sent back - but in theory you can dos the bot via Telegram by sending the right commands repeatedly, so i think this should be the way to go.

Anyway, it's not something we officially support.
