### ISSUE TITLE
Can't Add cryptocurrency of Bittrex because of Poloniex

### ISSUE THREAD

**Issue by dertione** [gcarq/freqtrade#19]
Hello !
I am Happy to meet you and your bot :) !
I use it since 3 days and I make profit, thank you for that.
I have some Idea and one issue for you if you permit :
- I can't trade money present on Bittrex and not on Poloniex (with Poloniex disable)
- I read the last issues. I compare the hour if buying with the actual chart and effectively, we have 1/2min of delay to make better profit. It is due to the refresh of 1min ?
-Do you think use 2 strategies is better than one ? (For example we study the trend of the chart and if it is down, we use one and if it is up another one ?)

I am developer engineer but newbie of trading, i think, i can help you to implement new strategies or API if you are some Idea but you have lack of time.

Thank you for Reading.

**Comment by gcarq** [comment]
Hi,

I'm glad that you like it.
What error do you get when trading with Bittrex? A stacktrace or some log messages would help a lot. Poloniex support will be dropped soon because it was not properly implemented in the first place.

To your question if two strategies are better than one: Yes I think so, we are currently experimenting on `develop` branch with different trading strategies (and combinations). Look at the latest PR from @vertti if you are interested: https://github.com/gcarq/freqtrade/pull/20

Sure, PR's are always welcome, but there are no fixed milestones yet due to lack of spare time, so for now just raise a Github issue if you want to discuss/implement an idea :-)

cheers

**Comment by dertione** [comment]
I am bot on my computer but the trader don't start because the money X is not on Poloniex (After call of API) and i have disable Poloniex before or course lol.
I will open pull request for my Idea thank you :)

Cheers

**Comment by gcarq** [comment]
Ah ok I see. If you change the exchange in the config you have to delete or rename `tradesv2.sqlite` manually, because in this db there is no reference where the coin has been bought

**Comment by dertione** [comment]
ok thx :) !
