### ISSUE TITLE
How to install it on Windows?

### ISSUE THREAD

**Issue by Owdr** [gcarq/freqtrade#222]
Hey! I have some problems on Windows 7 starting with command "> source .env/bin/activate". Please, help me anyone!

**Comment by Thuruv** [comment]
In **Windows** you have to activate the environment via `\path\to\env\Scripts\activate`. Let us know the result.

**Comment by gcarq** [comment]
It is possible that the file is called `activate.bat` on windows

**Comment by Owdr** [comment]
Seems to work! My command line start with `(.env)\path\freqtrade-develop>`. 
But now I get error with command `$ ./freqtrade/main.py`. 
I just run it this way: 
```
(.env)\path\freqtrade-develop>cd freqtrade
(.env)\path\freqtrade-develop\freqtrade>main.py
```
Error: 
`line 28 def refresh_whitelist(whitelist: Optional[List[str]] = None) -> None: SyntaxError: invalid syntax` 
on syntax ":" before whitelist.

Thanks!

**Comment by gcarq** [comment]
@Owdr You need python3.6+. What is your python version?
```
$ python --version
```

**Comment by Owdr** [comment]
Python 3.6.0. Yea! It work! :)
In fine manual installation on Windows:
```
#copy paste config.json to \path\freqtrade-develop\freqtrade
>cd \path\freqtrade-develop
>python -m venv .env
>cd .env\Scripts
>activate.bat
>cd \path\freqtrade-develop
>pip install -r requirements.txt
>pip install -e .
>cd freqtrade
>python main.py
```

Thank you so much! Very good work!

**Comment by gcarq** [comment]
You're welcome. I'm glad that it works.

**Comment by wardj1999** [comment]
For an even easier way of doing this with docker....
1. Download Pycharm CE
2. download this git as a zip
3. extract the zip and open freqtrade-develop as a project in pycharm
4.open the dockerfile from freqtrade-develop in pycharm and download the docker plugin when it asks you to
5. In the dockerfile add this line below # Install Dependencies 
`COPY config.json.example /freqtrade/config.json`
6. Open config.example.json and either input your information for telegram or turn it to false and dry run to true too.
7. In the Pycharm code area where the lines are number next to the first number is two green run buttons click it then click build image
8. when the image finishes building disconnect from the docker instance from the bottom left hand side the red stop square and then reconnect with the green run button. This should populate the containers and images section of docker
9. Right click the image you just made you can see the name in the docker console after it finishes building it will say "Successfully built (2884cb2e681e)" find that image (2884cb..etc) click create container a pop up will pop open click run.

Now mind you every time you change the strategy or anything you will have to rebuild and deploy the image. I found this works best on 64 bit windows systems with docker build tools installed. Other than that you have to deal with figuring out how to compile TA-lib on 64bit machine and ive yet to be able to do that.

Also this is sort of a question too. Since the image builds and runs succesfully im assuming that TA-Lib is working correctly but you would never be able to know because it just wouldnt fill the buy database and throws no errors when TA-lib isnt work runs fine just isnt able to find a crypto to buy. I was wondering if there was a way to check TA-lib while running the docker image?

**Comment by xmatthias** [comment]
honestly, i don't think ta-lib (the python package) will install if the ta-lib (the library) is not installed.
Missing the python package `ta-lib` however should prevent the bot from starting ... as it's imported in the strategy.

**Comment by wardj1999** [comment]
Yea idk i was struggling a lot with the python package i installed the library and recompiled It on my 64bit system but the package kept throwing unresolved errors i managed to pull the python package and compile from another source and It installed but when i looked into the strategy all the words associated where lit up with errors but the freqtrade program still ran with no errors just wasn’t buying anything. I have managed to successfully boot It on the docket image though

**Comment by anhtuantt** [comment]
Hello, 
I'm installing the freqtrade on Windows (Python 3.6.1, Windows 10 and follow Windows installation in the github page), successfully ran activate.bat and installed TA-Lib from wheel, but at this line "pip install -r requirements.txt", the error was thrown:
 Running setup.py install for idna-ssl ... done
  Running setup.py install for toolz ... done
  Running setup.py install for cytoolz ... error
  building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Not sure what i was missing, please give me an advices.
Thanks,
Tuan Nguyen.
