### ISSUE TITLE
Buying up to average out losses [Request for Enhancement]

### ISSUE THREAD

**Issue by thorK65** [gcarq/freqtrade#444]
**Problem:**

Even the best strategy doesnt now when bitcoin is going crazy which will lead often to massive drops -> bags.

An implementation of buying more than once of a particular coin would allow to average out the loss. 
If a price drops before it was sold with profit the bot  would buy again at the next buying signal for the same stake amount to average out. The average buying price would be stored in the database as buying price of the particular coin. This would happen over and over again till the average price would give a profit when selling. To make it more complex one could set up a max buying up of x-times.

I think this would be a very important part for all strategies.

Rebuying would help to get rid of bags/ avoid bags

**Comment by shusso** [comment]
thanks for the suggestion @thorK65 👍 Currently in develop we moved away from developing "official" bot strategy so that we just offer some default strategy that users can overwrite. Feel free to join our [slack](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE) channel `#sharing-strategies` where people share their developed strategies for the bot. And there you can get help if you want to develop that strategy. We always welcome PRs for either example or then to replace the current strategy.
