### ISSUE TITLE
Custom strategy file hierarchy of params: strategy (local) params over global config.json?

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#461]
Currently param hierarchy  =
1. param via command line
2. global config.json
3. custom strategy file
(not even sure about number 1)

Should this not be?
1. param via command line
2. custom strategy file
3. global config.json (fall back)

And if so, maybe also add a quick reference to this hierarchy in the readme

**Comment by glonlas** [comment]
You are right in the order. The hierarchy is: 
1. param via command line (Take over config)
2. config.json (take over strategy)
3. custom strategy file

Why this order? 
Because the strategy file can be shared between users. But different users will want to have custom configuration without changing the strategy source code. 

What I did, I removed the unwanted configuration from my main `config.json`. Means I removed: `minimal_roi`, `stoploss`, and `ticker_interval`.

> And if so, maybe also add a quick reference to this hierarchy in the readme

You are right, I will add it.

**Comment by seansan** [comment]
Although I follow your reasoning

I would expect a strategy to contain all settings. So if defined in
strategy then override config.

Suppose we don’t do this. Then using someone’s strategy can have different
effects because without knowing you are using some global config Param
giving different results

So if a startegy defines some setting then it is based on it. And thus sets
it and hereby overrides the others
