### ISSUE TITLE
Exception on wallet in maintenance mode

### ISSUE THREAD

**Issue by xsmile** [gcarq/freqtrade#60]
A wallet in maintenance mode caused an exception resulting in a stopped bot (dev branch).

```
Traceback (most recent call last):
  File "/usr/bin/freqtrade", line 4, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 269, in main
    app(_CONF)
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 249, in app
    _process()
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 57, in _process
    handle_trade(trade)
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 137, in handle_trade
    current_rate = exchange.get_ticker(trade.pair)['bid']
  File "/usr/lib/python3.6/site-packages/freqtrade/exchange.py", line 118, in get_ticker
    'bid': float(data['result']['Bid']),
TypeError: float() argument must be a string or a number, not 'NoneType'
2017-10-07 03:55:46,165 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
```

Currently it is still offline and I logged the API resonse:

```
{'success': True, 'message': '', 'result': {'Bid': None, 'Ask': None, 'Last': None}}
```

**Comment by gcarq** [comment]
I'm going to close this, because there is not much we can do here

**Comment by xsmile** [comment]
If I didn't miss anything important, checking the price lists in `result` for `None` and ignoring the pair while no usable data is found should be enough. This way the bot will keep running and trade other pairs.
Not sure how this is connected to the telegram error though.

**Comment by gcarq** [comment]
That is true, but that would mean we need to implement a own exception for this type of error for multiple endpoints and pollute the code with bittrex internals. IMO this should be reported to bittrex, because responding with `'success': True` is no sane option here.
I agree if it happens more often we need to implement some workaround.

I'm also not sure about the telegram error, I guess this is just coincidence, because the exception occurs in the main thread.

I'm keeping this issue open for discussion.

**Comment by xsmile** [comment]
> Always check the success flag to ensure that your API call succeeded.

I'm not a big fan of their API either :)

You are right, please feel free to close this issue again. It might be better to open a new one specifically for these weird API workarounds.
