### ISSUE TITLE
INSUFFICIENT_FUNDS

### ISSUE THREAD

**Issue by jetienne** [gcarq/freqtrade#63]
Step 1: bot "BITTREX: Buying BTC/LUN at rate 0.001101"
Step 2:  Status: Got RuntimeError:
Traceback (most recent call last):
  File "main.py", line 261, in app
    _process()
  File "main.py", line 42, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "main.py", line 198, in create_trade
    order_id = exchange.buy(pair, open_rate, amount)
  File "/app/exchange.py", line 62, in buy
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: INSUFFICIENT_FUNDS

Nothing happened between step 1 and step 2. My bot is launched from the master branch.

Possibly related to this bug, 
/status
=> Trade ID: 1
Current Pair: BTC_LUN
Open Since: 5 hours ago
Amount: 72.66055712
Open Rate: 0.00110101
Close Rate: None
Current Rate: 0.00110001
Close Profit: None
Current Profit: -0.09%
Open Order: None

/forcesell 1
>> BITTREX: Selling BTC/LUN at rate 0.001093 (profit: -0.74%)

Sell is done (I have checked on bittrex), but /status still gives the Trade ID as an open order.

**Comment by EricLim110** [comment]
Are you using the files from the ``master`` branch? There is an issue with forcesell trades not being removed. This issue was fixed in the ``develop`` branch, try using the files from there instead.

I had the same issue before and @gcarq did suggest me to stick to the ``develop`` branch for now as the bot is still in the development stage.

Personally, I would do dry run first to make sure everything is running well before disabling it. Hope this helps you out!

**Comment by jetienne** [comment]
Upgraded master, I did not have this issue anymore.
